#!/usr/bin/env bash
# ============================================================
#  Screenshots of the Android app, from a running emulator or a plugged-in
#  phone, into docs/screenshots/.
#
#      ./tools/screenshots.sh
#
#  It drives device-only mode, so it needs no Supabase project and no Google
#  account — the app is fully usable without either, and that is what makes
#  this runnable on a machine that has never been set up.
#
#  The ledger it photographs is generated by the web repo's
#  tools/demo-ledger.js, converted to the Kotlin cache format by
#  tools/demo-cache.mjs, so the phone and the browser are photographed
#  holding exactly the same money.
# ============================================================
set -euo pipefail

PKG=com.hanifedma.tally
OUT="$(cd "$(dirname "$0")/.." && pwd)/docs/screenshots"
ADB="${ANDROID_HOME:-$HOME/AppData/Local/Android/Sdk}/platform-tools/adb"
mkdir -p "$OUT"

if ! "$ADB" get-state >/dev/null 2>&1; then
  echo "No device. Start an emulator first:" >&2
  echo "  \$ANDROID_HOME/emulator/emulator -avd <name> -no-boot-anim" >&2
  exit 1
fi

say() { printf '\n== %s\n' "$1"; }
shot() { sleep "${2:-2}"; "$ADB" exec-out screencap -p > "$OUT/$1.png"; echo "  $1.png"; }
tap_text() {
  # Tap the centre of the first node whose text contains $1. Reading the
  # hierarchy rather than hard-coding coordinates, so this survives a
  # different screen size or a wording change.
  local needle="$1"
  "$ADB" shell uiautomator dump /sdcard/ui.xml >/dev/null 2>&1
  local bounds
  bounds=$("$ADB" shell cat /sdcard/ui.xml \
    | tr '>' '\n' \
    | grep -F "$needle" \
    | grep -o 'bounds="\[[0-9]*,[0-9]*\]\[[0-9]*,[0-9]*\]"' \
    | head -1 \
    | grep -o '[0-9]*')
  if [ -z "$bounds" ]; then echo "  (no node matching: $needle)" >&2; return 1; fi
  local x1 y1 x2 y2
  read -r x1 y1 x2 y2 <<< "$(echo "$bounds" | tr '\n' ' ')"
  "$ADB" shell input tap $(( (x1 + x2) / 2 )) $(( (y1 + y2) / 2 ))
  sleep 1
}

say "Installing the debug build"
./gradlew --quiet assembleDebug
"$ADB" install -r -g app/build/outputs/apk/debug/app-debug.apk >/dev/null
"$ADB" shell pm clear "$PKG" >/dev/null

say "First run — the way in with no account"
"$ADB" shell am start -n "$PKG/.MainActivity" >/dev/null
shot "01-setup" 4
tap_text "device only" || tap_text "without an account"
shot "02-empty" 3

say "Loading the same demo ledger the web screenshots use"
node ../tally/tools/demo-cache.mjs /tmp/tally-cache.json
"$ADB" push /tmp/tally-cache.json /sdcard/cache-local.json >/dev/null
"$ADB" shell "run-as $PKG mkdir -p files/tally" || true
"$ADB" shell "run-as $PKG sh -c 'cat /sdcard/cache-local.json > files/tally/cache-local.json'"
"$ADB" shell am force-stop "$PKG"
"$ADB" shell am start -n "$PKG/.MainActivity" >/dev/null
shot "03-log" 5

say "The other screens"
tap_text "Insights"; shot "04-insights" 2
tap_text "Accounts"; shot "05-accounts" 2
tap_text "Log";      sleep 1

say "The editor"
"$ADB" shell input tap 950 2150   # the add button, bottom right
shot "06-editor" 3
"$ADB" shell input keyevent KEYCODE_BACK
sleep 1

say "Settings, and light mode"
tap_text "☰" || "$ADB" shell input tap 1000 170
shot "07-settings" 3
"$ADB" shell input keyevent KEYCODE_BACK
sleep 1

echo
echo "Done — $OUT"
"$ADB" shell rm -f /sdcard/ui.xml /sdcard/cache-local.json >/dev/null 2>&1 || true
